### ISSUE TITLE
Soft UX/UI re-design 

### ISSUE THREAD

**Issue by pablortsal** [voidcosmos/angular-communities#31]
Early stage projects always tend to have a  weird situation talking about UX/UI, if we want this project to grow we need to provide users an experience where they feel conformable and where they want to use it again and recommend it

I want to propose a soft re-design and bring a more polish UX/UI interface.

![Frame 1 (1)](https://user-images.githubusercontent.com/369639/81581139-a16ba380-93ae-11ea-8a91-03aa9043ec01.png)
![Frame 2](https://user-images.githubusercontent.com/369639/81581142-a3356700-93ae-11ea-9288-f538f9ff73f5.png)

**More detailed design here:**
Figma Link -> https://www.figma.com/file/7aClC5BdN8LW9Plbkg3nOO/Angular-Communities?node-id=0%3A1

I didn't code this design yet, but if you like it I'm definitely going to do it.

What do you think? Could be a better or worse feature?

_(PS I'm not a designer, just trying to help :P )_

**Comment by tonivj5** [comment]
Amazing! It looks really cool :clap:

IMHO (and I'm not either a designer at all :laughing:), I would make the logos bigger and would remove the border from the second image (community info) and fill the space.

Great work with the proposal :tada::clap:

**Comment by oxigenao** [comment]
Sounds, good @tonivj5 , later I will send you a new design with those changes

**Comment by oxigenao** [comment]
Sorry for the delay guys, i just update the design with the proposed changes, I expect to start working on it this week, if anyone want to help with the implementation let me know so we could sincronize the work :)


![Frame 3](https://user-images.githubusercontent.com/369639/82155291-26a1fd00-9874-11ea-82cf-83ab94557226.png)

**Comment by tonivj5** [comment]
Looks good!! :+1:

@Caballerog or @NyaGarcia, any thought?

If you need any help, let me know :smile:

**Comment by Caballerog** [comment]
In my opinion, this design is fresh, how can I help you to implemented? 

I prefer used the official module GridLayout and FlexLayout from FlexLayoutModule. Also, I love use a good architecture in SASS/CSS, this feature is in a early-stage, so you can begin the work.

Thanks for your time!

**Comment by oxigenao** [comment]
Hey guys, sorry for the delay, those past days I was really busy.

About the css decisión I think using just pure css flex could be achieved, i will try to implement the first steps the nexts days and send you a pull request.

**Comment by tonivj5** [comment]
> I think using just pure css flex could be achieved

I'm with you :+1:

> i will try to implement the first steps the nexts days and send you a pull request.

Cool! Let us know if you need anything :smiley:

**Comment by oxigenao** [comment]
Hey Guys, I just finished the first interation on the redesing, its not fully completed, but since I dont have so much time, maybe could be a good entry points for other to continue, I  created some new components and componentize some code.

**Comment by Caballerog** [comment]
This Issue was integrate into the code :-) 

Thanks everybody!

**Comment by tonivj5** [comment]
Really good work here @pablortsal and @Caballerog :clap: The new design is pretty cool
