### ISSUE TITLE
[Communities] Add Angular Madrid

### ISSUE THREAD

**Issue by karol-depka** [voidcosmos/angular-communities#36]
https://www.meetup.com/es/Angular_Madrid/

**Comment by karol-depka** [comment]
Also, checking https://www.meetup.com/es/topics/angularjs/es/

**Comment by karol-depka** [comment]
I can add the data to the json.

**Comment by tonivj5** [comment]
> I can add the data to the json.

Cool, take it

**Comment by NyaGarcia** [comment]
We haven't added AngularMadrid because the meetup has been inactive for 7+ months. If activities are resumed, we'll be happy to add it :) 

Closing until further notice, feel free to reopen whenever AngularMadrid activity is resumed.
