### ISSUE TITLE
Wrong icon for ngArab

### ISSUE THREAD

**Issue by MitkoTschimev** [voidcosmos/angular-communities#37]
**Describe the bug**

**To Reproduce**
1. Search for ngArab

**Expected behavior**
Th ngArab logo is provided

**Screenshots**
![image](https://user-images

**Comment by Caballerog** [comment]
Hello @MitkoTschimev 

The image link was not written correctly.

You could retype the link so we can replace it.

Thank you.

**Comment by MitkoTschimev** [comment]
:( I don't know the link to the ngArab logo. I'm only the organizer of ngDubai and this one is fine ;)

**Comment by Caballerog** [comment]
Hi,

I think that I fixed the ngArab logo when I added ngDubai (now you can see
the ngArab logo) :-P

Thanks for your notice.

----------------------------------------------------------------------------

Dr. Carlos Caballero González PTFP Sistemas y Aplicaciones Informáticas -
Junta de Andalucía Blog: https://www.carloscaballero.io LinkedIn:
http://lnkd.in/xVG3qV Twitter: http://www.twitter.com/carlillo GitHub:
http://www.github.com/caballerog
----------------------------------------------------------------------------


ᐧ

**Comment by NyaGarcia** [comment]
NgArab logo was corrected in #38, closing.
