### ISSUE TITLE
SonarQube Integration

### ISSUE THREAD

**Issue by Caballerog** [voidcosmos/angular-communities#52]
**Is your feature request related to a problem? Please describe.**
We should use a tool to measure the QA of our code. 

**Describe the solution you'd like**
We should integrate in our CI/CD workflow the SonarQube to measure the QA of our project.

**Comment by oidacra** [comment]
Can i work in this issue?

**Comment by NyaGarcia** [comment]
@oidacra Of course! Any help at all is welcome :) Any ideas on how to implement this?

**Comment by oidacra** [comment]
> @oidacra Of course! Any help at all is welcome :) Any ideas on how to implement this?

We can use https://sonarcloud.io/ is free for open-source projects. I used in 2 personal projects.

**Comment by Caballerog** [comment]
I've taken a quick quick look at the tool, and it seems very useful. It would avoid us having to install an instance of SonarQube,

Do you know if it could be configured to do the analysis every time we push to master?

For my part, you can start configuring it!

**Comment by oidacra** [comment]
> I've taken a quick quick look at the tool, and it seems very useful. It would avoid us having to install an instance of SonarQube,
> 
> Do you know if it could be configured to do the analysis every time we push to master?
> 
> For my part, you can start configuring it!

Hi, i have the Github Action ready, but i need the configuration of the sonarcloud. I add the badge to readme file.
![Screen Shot 2020-06-26 at 1 46 10 AM](https://user-images.githubusercontent.com/1909643/85828888-f5f49380-b74e-11ea-8a2d-bab04e52a26b.png)
